version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(ci)"

  - package-ecosystem: terraform
    directories:
      - "/terraform/modules/**"
      - "/terraform/examples/**"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(terraform)"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore(deps)"
