{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: {{ .Values.externalSecret.clientIdRemoteKey }}
    - secretKey: client_secret
      remoteRef:
        key: {{ .Values.externalSecret.clientSecretRemoteKey }}
{{- end }}
