{{- if and .Values.enabled .Values.bootstrap.enabled }}
{{- $prefix := .Values.global.secretPrefix | default .Values.global.namespace }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nocodb.fullname" . }}-bootstrap
  namespace: {{ include "nocodb.namespace" . }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ .Values.bootstrap.externalSecrets.secretStore | default "gcp-secretstore" }}
    kind: {{ .Values.bootstrap.externalSecrets.secretStoreKind | default "ClusterSecretStore" }}
  refreshInterval: {{ .Values.bootstrap.externalSecrets.refreshInterval | default "1h" }}
  target:
    name: {{ include "nocodb.fullname" . }}-bootstrap
    creationPolicy: Owner
  data:
    - secretKey: admin-email
      remoteRef:
        key: {{ $prefix }}-nocodb-admin-email
    - secretKey: admin-password
      remoteRef:
        key: {{ $prefix }}-nocodb-admin-password
    - secretKey: ro-password
      remoteRef:
        key: {{ $prefix }}-nocodb-ro-password
{{- end }}
